config/routes.rb
Rails.application.routes.draw do

# resources :food
root 'food#index'
get '/generate_random' => 'food#generate', :as => :generate
get '/updates' => 'food#updates', :as => :updates


end

app/models/food.rb
class Food < ActiveRecord::Base



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/food_controller.rb
  class FoodController < ApplicationController

  def index
    food_count = Food.count
    food_random = rand(1..food_count)
    @food = Food.find(food_random).name.gsub(/\w+/, &:capitalize)

    @random_question_array = ["What do you feel like eating today?", "What do you crave now?", "I could so go for ... ", "Today is the day I eat", "You know you want...", "Anyone would have suggested...", "If I had to say...", "You must crave...", "Let me guess...", "May I suggest...", "What does your stomach want?", "What does your tummy want?", "You tummy is all for", "Your tummy says HELLO to", "Your face tells me that you want...", "Open your arms and embrace", "Don't waver, you want", "Thank me later, get...", "Live to eat, enjoy...", "Your money wants...", "Your tummy wants...", "You subconsciously smell...", "Don't doubt, don't resist, eat", "Close your eyes and imagine", "Hands down, you definitely want", "You secretly want", "A foodie would recommend"]
    @random_question = @random_question_array.shuffle.first
    @adjectives_array = ["a super delicious", "a mouth-watering", "an irresistable", "a heavenly", "a divine taste of", "an incredible", "a superb", "an appetizing", "a satisfying", "a beastly", "a super tasty", "an uberdelicious", "a quality", "a perfecto", "a five-star", "a dream-fulfilling", "a supreme", "a fantastic", "a wonderful", "an amazing"]
    @adjectives = @adjectives_array.shuffle.first

    sleep 1

    respond_to do |format|
      format.html { render('index') }
    end

    # offset = rand(Food.count)
    # @rand_record = Food.offset(offset).first

    # @food = Food.random.without(params[:last_ids]).limit(1)
    # binding.pry

  end

  def generate
    food_count = Food.count
    food_random = rand(1..food_count)
    @food = Food.find(food_random).name

    @random_question_array = ["What do you feel like eating today?", "What do you crave now?", "I could so go for ... ", "Today is the day I eat", "You know you want...", "Anyone would have suggested...", "If I had to say...", "You must crave...", "Let me guess...", "May I suggest...", "What does your stomach want?", "What does your tummy want?", "You tummy is all for", "Your tummy says HELLO to", "Your face tells me that you want...", "Open your arms and embrace", "Don't waver, you want", "Thank me later, get...", "Live to eat, enjoy...", "Your money wants...", "Your tummy wants...", "You subconsciously smell...", "Don't doubt, don't resist, eat", "Close your eyes and imagine", "Hands down, you definitely want", "You secretly want", "A foodie would recommend"]
    @random_question = @random_question_array.shuffle.first
    @adjectives_array = ["a super delicious", "a mouth-watering", "an irresistable", "a heavenly", "a divine taste of", "an incredible", "a superb", "an appetizing", "a satisfying", "a beastly", "a super tasty", "an uberdelicious", "a quality", "a perfecto", "a five-star", "a dream-fulfilling", "a supreme", "a fantastic", "a wonderful", "an amazing"]
    @adjectives = @adjectives_array.shuffle.first


    sleep 1

    respond_to do |format|
      format.js
    end
  end

  def updates
    @time = Time.now.strftime("%d/%m/%Y %H:%M")
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/views/food/_food.html.erb
  <h3 id="questions"><%=@random_question%></h3>

  <p id="adjectives"><%=@adjectives %></p>
  <h2 id="foodselected"><%= @food %> </h2>


  <div id="reroll" data-toggle="tooltip" data-placement="bottom" title="Try again">
    <!-- <%= link_to "Reroll", generate_path, :remote => true, :id => 'reroll_link' %> -->
    <%= link_to '<i class="fa fa-spoon" aria-hidden="true"></i>&nbsp<i class="fa fa-frown-o fa-2x fa-spinn" aria-hidden="true"></i>&nbsp<i class="fa fa-coffee " aria-hidden="true"></i>'.html_safe, generate_path, :remote => true, :id => 'reroll_link' %>
  </div>







<!-- Loading icon and functionality -->
  <div id="spinner">
      <!-- <%= image_tag "foodloading.gif", :class => 'foodspinner' %> -->
      <p> <i class="fa fa-spinner fa-pulse fa-fw"></i>&nbsp Finding the right food for you...</p>
  </div>

  <script type="text/javascript">
      $("#spinner").hide(); // Hide the spinner by default
      $("#reroll").show(); // But show the menu

      $("#reroll_link").click(function (event) {
          console.log("onClickEvent() called")
          $("#spinner").show();
          $("#reroll").hide();
      });
  </script>

app/views/food/generate.js.erb
$('div#food_container').html("<%= j render(:partial => 'food/food', :locals => { :food => @food }) %>");


$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})

app/views/food/index.html.erb
<div id="food_container">

  <!-- <p> <%= Food.order("RANDOM()").first.name %></p> -->
  <!-- <p><%= @food %> </p> -->
  <%= render 'food/food' %>


</div>

<div style="text-align: right">
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_donations">
<input type="hidden" name="business" value="lhero_@hotmail.com">
<input type="hidden" name="lc" value="AU">
<input type="hidden" name="item_name" value="Donation appreciated. If >$10, you can suggest a dish to be added. If >$50, increase chance of your dish.">
<input type="hidden" name="no_note" value="0">
<input type="hidden" name="currency_code" value="AUD">
<input type="hidden" name="bn" value="PP-DonationsBF:btn_donateCC_LG.gif:NonHostedGuest">
<input data-toggle="tooltip" data-placement="left" title="For more selections and background pictures in the future" type="image" src="https://www.paypalobjects.com/en_AU/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_AU/i/scr/pixel.gif" width="1" height="1">
</form>
</div>

app/views/food/updates.html.erb
<div class="container">
  <div class="jumbotron">
    <p style="font-weight: bold">05/02/17</p>
    <p style="font-size:15px">Updates coming in the future will include: </p>
      <li style"font-size:15px">More food to be added to the list</li>
      <li style"font-size:15px">More variety of questions and adjectives</li>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whattoeat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=Bangers|Copse|Dancing+Script|Hind+Vadodara|Lobster" rel="stylesheet"></head>
  <link href="https://fonts.googleapis.com/css?family=Barrio|Kaushan+Script|Pangolin|Righteous" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <!-- BS JS -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<body>

  <div class="body-inner">
    <div class="body-inner-inner">

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
          <a class="navbar-brand text-center">
            <p class="nav-text"> What should I eat &nbsp&nbsp<i class="fa fa-cutlery fa-cut" aria-hidden="true"></i></p>
          </a>
      </div>
    </nav>

      <%= yield %>
    </div>
  </div>

  <!-- <footer class="footer">
      <p class="text-muted">Will</p>
  </footer> -->


</body>
</html>